### ISSUE TITLE
EVM error OpcodeNotFound when running `deploy_evm`

### ISSUE THREAD

**Issue by JSeam2** [zkonduit/ezkl#349]
### Describe the bug
Deployment of the `Verifier.sol` may not work depending on the version of solidity and the networks it is deployed on. 

### Expected behaviors
The deployment should work as expected, or provide some helper error messages as to what versions of the EVM to deploy on. 

### Steps to reproduce the bug
1. Compile the attached Verifier.sol with solc v0.8.0 onwards
2. Deploy on a variety of EVM versions, the Verifier.sol might not be deployed due to changes in opcodes in the EVM.

### Additional Information
[test.sol.zip](https://github.com/zkonduit/ezkl/files/12002460/test.sol.zip)

**Comment by Neurone** [comment]
That is due to the introduction of `PUSH0` opcode in post-Shangai networks. So, if you compile using `solc >= 0.8.20` you end up using that opcode, so bytecode is not compabile with pre-Shangai networks.

It's not something that can be fixed by this project. The only option is to force the user to use a non updated solc release, setting the smart contracts like this:

```solidity
pragma solidity >=0.8.17 <0.8.20;
```

But I discourage this approach. Limiting the solc version should be done because of the content of the smart contract, to protect the user, not to limit their possibilities. `0.8.20` and `0.8.21` in fact introduced fixes and improvements the users have the right to use, they just need to be aware they need to use a solc < 0.8.20 if the want to address per-Shangai networks.

**Comment by alexander-camuto** [comment]
@ethan-crypto can we add @Neurone's comments to the docs
